In [11]:
import numpy as np

In [13]:
np.__version__

'1.26.4'

In [15]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

## CREATING ARRAYS

In [18]:
my_list=[0,1,2,3,4,5] 
my_list

[0, 1, 2, 3, 4, 5]

below code we are converting list to array

In [21]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
type(arr)

numpy.ndarray

In [25]:
type(my_list)

list

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
np.arange(3.0)

array([0., 1., 2.])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(20,15)

array([], dtype=int32)

In [39]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [41]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [43]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [45]:
ar=np.arange(-20,30)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29])

In [47]:
np.arange(10,10)

array([], dtype=int32)

In [49]:
np.arange()

TypeError: arange() requires stop to be specified.

In [51]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [54]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [58]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [60]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [66]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
np.ones(3)

array([1., 1., 1.])

In [71]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [73]:
np.twos(2,3)

AttributeError: module 'numpy' has no attribute 'twos'

In [75]:
np.ones(n)

NameError: name 'n' is not defined

In [78]:
rand(3,2)

NameError: name 'rand' is not defined

In [80]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [82]:
np.random.rand(3,2)

array([[0.66534296, 0.51848344],
       [0.64443659, 0.83480997],
       [0.93833397, 0.8041233 ]])

In [84]:
np.random.rand(4)

array([0.76750736, 0.27826481, 0.62149871, 0.81621676])

In [86]:
np.random.randint(3,5)

3

In [88]:
np.random.randint(1,24)

6

In [90]:
np.random.randint(0,1)

0

In [92]:
np.random.randint(1,40,5)

array([ 4,  5, 10, 10,  1])

In [94]:
np.random.randint(0,10,5)

array([2, 2, 9, 7, 9])

In [96]:
np.random.rand(3)

array([0.02607062, 0.32065883, 0.55982338])

In [105]:
np.random.randint(10,40,(10,10))

array([[21, 18, 38, 14, 18, 15, 15, 26, 23, 22],
       [26, 31, 22, 30, 24, 31, 11, 20, 33, 26],
       [11, 14, 15, 34, 38, 24, 17, 19, 15, 34],
       [12, 26, 12, 13, 37, 19, 28, 11, 25, 24],
       [25, 28, 32, 33, 31, 18, 37, 17, 22, 39],
       [13, 20, 16, 37, 37, 20, 21, 23, 28, 12],
       [25, 13, 18, 31, 24, 27, 10, 16, 27, 14],
       [31, 37, 26, 36, 23, 23, 17, 25, 32, 15],
       [19, 36, 16, 33, 21, 21, 21, 22, 18, 19],
       [22, 29, 10, 23, 28, 16, 21, 11, 10, 35]])

In [113]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [124]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [126]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [138]:
b=np.random.randint(10,20,(5,4))
b

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [140]:
type(b)

numpy.ndarray

In [142]:
b[:]

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [144]:
b[1:3]

array([[14, 10, 16, 11],
       [10, 16, 16, 14]])

In [146]:
b[1,2]

16

In [148]:
b

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [150]:
b[1,-1]

11

In [152]:
b[2:3]

array([[10, 16, 16, 14]])

In [154]:
b[0:-2]

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14]])

In [163]:
b[0,2]

16

In [165]:
b[-4,2]

16

In [167]:
b[-4,-2]

16

In [169]:
b

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [171]:
b[2:3]

array([[10, 16, 16, 14]])

In [173]:
b

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [176]:
b[0:-2]

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14]])

In [178]:
b[0:2]

array([[10, 16, 16, 13],
       [14, 10, 16, 11]])

In [191]:
b[0,2]

16

In [193]:
b[0,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [195]:
b[-5,-3]

16

In [197]:
b[-4,2]

16

In [199]:
np.random.randint(20,30,(4,4))

array([[24, 27, 28, 23],
       [24, 24, 22, 26],
       [29, 29, 21, 28],
       [25, 24, 20, 20]])

In [201]:

b

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

In [203]:
b[-4,-2]

16

In [205]:
b[-4:2]

array([[14, 10, 16, 11]])

In [207]:
b[:]

array([[10, 16, 16, 13],
       [14, 10, 16, 11],
       [10, 16, 16, 14],
       [17, 15, 19, 18],
       [13, 14, 12, 19]])

# OPERATIONS

In [220]:
a=np.random.randint(1,10,10)
a

array([6, 3, 6, 4, 9, 3, 1, 4, 6, 4])

In [222]:
id(a)

2056445475600

In [224]:
arr

array([0, 1, 2, 3, 4, 5])

In [230]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [11, 95, 41,  0, 13, 45, 30, 31,  2, 32]])

In [233]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [235]:
arr2[:]

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [11, 95, 41,  0, 13, 45, 30, 31,  2, 32]])

In [237]:
arr2[0:5]

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10]])

In [239]:
arr2[1,4]

58

In [241]:
arr2[-5,5]

24

In [243]:
arr2[-5,-5]

24

In [245]:
arr2

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [11, 95, 41,  0, 13, 45, 30, 31,  2, 32]])

In [247]:
arr2[-1,-2]

2

In [249]:
arr2[::-1]

array([[11, 95, 41,  0, 13, 45, 30, 31,  2, 32],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [80, 84, 64, 99, 11, 46, 15,  3,  0, 90]])

In [251]:
arr2

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [11, 95, 41,  0, 13, 45, 30, 31,  2, 32]])

In [253]:
arr2[::-2]

array([[11, 95, 41,  0, 13, 45, 30, 31,  2, 32],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6]])

In [255]:
arr2[::-3]

array([[11, 95, 41,  0, 13, 45, 30, 31,  2, 32],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [80, 84, 64, 99, 11, 46, 15,  3,  0, 90]])

In [257]:
arr2

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36],
       [78, 37, 92, 21, 26, 66,  9, 89, 53, 98],
       [24, 33, 44, 36, 86, 79, 36, 91,  4, 85],
       [11, 95, 41,  0, 13, 45, 30, 31,  2, 32]])

In [259]:
arr2[:-3]

array([[80, 84, 64, 99, 11, 46, 15,  3,  0, 90],
       [87, 81, 25, 45, 58, 29,  2, 99, 88,  6],
       [ 6, 76, 93,  8, 19, 13, 82, 51,  5, 91],
       [94, 54, 15, 92, 53, 72, 61, 38, 23, 38],
       [14, 42, 39, 18, 92, 43, 46, 16, 94, 10],
       [44, 17, 49, 43, 95, 24, 97, 60, 24, 45],
       [32,  2, 93,  2, 69, 40, 41, 56, 79, 36]])

In [261]:
arr

array([0, 1, 2, 3, 4, 5])

In [263]:
arr.max()

5

In [265]:
arr.min()

0

In [267]:
arr.sum()

15

In [269]:
arr.mean()

2.5

In [271]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [281]:
from numpy import *
a=array([1,2,3,4,5,6,7])
median(a)

4.0

# Without work on import* can you please find the median, mode)

In [291]:
arr

array([0, 1, 2, 3, 4, 5])

In [295]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [297]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [299]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [301]:
arr.reshape(2,4})

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (2377609563.py, line 1)

In [305]:
arr.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [303]:
arr

array([0, 1, 2, 3, 4, 5])

In [310]:
arr.reshape(2,3,order='C')  #print element using c-type indexing

array([[0, 1, 2],
       [3, 4, 5]])

In [312]:
arr.reshape(3,2,order='F')   # print element with fortran 

array([[0, 3],
       [1, 4],
       [2, 5]])

In [314]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [316]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [318]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [326]:
arr.reshape(1,3,order='A')

ValueError: cannot reshape array of size 6 into shape (1,3)

In [329]:
arr

array([0, 1, 2, 3, 4, 5])

In [331]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [333]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [335]:
arr(1,4)

TypeError: 'numpy.ndarray' object is not callable

In [337]:
arr(6,1)

TypeError: 'numpy.ndarray' object is not callable

# INDEXING

In [348]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [350]:
row=5
col=6

In [352]:
row

5

In [354]:
col

6

In [356]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [358]:
mat[row,col]

56

In [360]:
mat[5,6]

56

In [362]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [364]:
col=7

In [366]:
mat[col]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [368]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [370]:
mat[:,col]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [374]:
mat[row,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [376]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [378]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [380]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [382]:
row

5

In [384]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [386]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [388]:
mat[row:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [390]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [392]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [394]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [396]:
mat[1,4]

14

In [398]:
mat[1:5]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [400]:
mat[4:-4]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [402]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [404]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [406]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [408]:
mat[6:9]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [410]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [412]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [414]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [416]:
mat[:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [418]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [420]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [422]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [424]:
mat[::-4]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [426]:
mat[::-6]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [428]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [430]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [432]:
mat[3:7,3:5]

array([[33, 34],
       [43, 44],
       [53, 54],
       [63, 64]])

In [434]:
mat[0,2]

2

In [436]:
mat[2,8]

28

In [438]:
mat[2:7]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [440]:
mat[2:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [442]:
mat[:9]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [444]:
mat[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [446]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [448]:
mat[2:7]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [450]:
mat[2,7]

27

In [454]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [452]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [458]:
mat[5:7,3:5]

array([[53, 54],
       [63, 64]])

In [468]:
mat[2:3,1:2]

array([[21]])

In [472]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [476]:
mat[2:3,4:5]

array([[24]])

# MASKING

In [481]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [483]:
id(mat)

2056452464368

In [491]:
mat[mat==50]

array([50])

In [497]:
mat[mat>=35]

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [499]:
mat[mat>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
       76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
       93, 94, 95, 96, 97, 98, 99])

In [501]:
mat[mat<=35]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [507]:
mat>99

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [509]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [511]:
mat<99

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]])

In [513]:
mat<=99

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [515]:
mat!=100

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])